name: Expo CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Expo prebuild
        run: npx expo prebuild --yes

      - name: Export app
        run: npx expo export
cd ~/Downloads/test-expo-ci
touch .trigger-again
git add .trigger-again
git commit -m "Trigger GitHub Actions again"
git push

ls -l .github/workflows

-rw-r--r--  1 stephenreganato  staff  456 Jul 21 16:53 expo-ci.yml


